FROM php:7.2-fpm

ENV TZ=Asia/Shanghai

RUN set -xe \
    && apt-get update \
    && apt-get install wget git vim -y \
    && docker-php-ext-install mysqli pdo_mysql \
    && cd ~ \
    && git clone --depth=1 git://github.com/phalcon/cphalcon.git \
    && cd cphalcon/build/php7/64bits \
    && phpize --clean \
    && phpize \
    && ./configure --with-php-config=php-config \
    && make && make install \